### ISSUE TITLE
Editing and deleting hosts doesn't work

### ISSUE THREAD

**Issue by Jille** [Jille/bitmpc#1]
When clicking edit, it deletes the host. When clicking delete, nothing happens.

**Comment by Jille** [comment]
I get these errors in the log when clicking delete. (And the app crashes. Might be somerthing memory related.)

  E/SurfaceFlinger(  569): not enough memory for layer bitmap size=1490944
  D/MemoryDealer(  569):   LayerBitmap (0x18bdd8, size=8388608)
  D/MemoryDealer(  569):     0: 0018be10 | 0x00000000 | 0x00024000 | F 
  D/MemoryDealer(  569):     1: 001f6760 | 0x00024000 | 0x000BC000 | A 
  D/MemoryDealer(  569):     2: 00229ad0 | 0x000E0000 | 0x000BC000 | A 
  D/MemoryDealer(  569):     3: 001f67d8 | 0x0019C000 | 0x0004A000 | F 
  D/MemoryDealer(  569):     4: 002633e8 | 0x001E6000 | 0x0016C000 | A 
  D/MemoryDealer(  569):     5: 00194010 | 0x00352000 | 0x0016C000 | A 
  D/MemoryDealer(  569):     6: 001cb360 | 0x004BE000 | 0x000CE000 | F 
  D/MemoryDealer(  569):     7: 002776c8 | 0x0058C000 | 0x0016C000 | A 
  D/MemoryDealer(  569):     8: 001bf9a0 | 0x006F8000 | 0x00108000 | F 
  D/MemoryDealer(  569):   size allocated: 6012928 (5872 KB)
  E/SurfaceFlinger(  569): resizing buffer 1 to (480,775) failed [fffffff4] Unknown error: -12
  E/SurfaceComposerClient(  569): surface (id=3, identity=13) is invalid, err=-12 (Out of memory)
  E/WindowManager(  569): Failure updating surface of Window{43745288 bitendian.bitmpc/bitendian.bitmpc.activity.BitMPC paused=false}size=(480x775), pos=(16,51)
  E/WindowManager(  569): java.lang.IllegalArgumentException
  E/WindowManager(  569):   at android.view.Surface.setSize(Native Method)
  E/WindowManager(  569):   at com.android.server.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner(WindowManagerService.java:7878)
  E/WindowManager(  569):   at com.android.server.WindowManagerService.performLayoutAndPlaceSurfacesLocked(WindowManagerService.java:7455)
  E/WindowManager(  569):   at com.android.server.WindowManagerService.access$1800(WindowManagerService.java:123)
  E/WindowManager(  569):   at com.android.server.WindowManagerService$H.handleMessage(WindowManagerService.java:7074)
  E/WindowManager(  569):   at android.os.Handler.dispatchMessage(Handler.java:99)
  E/WindowManager(  569):   at android.os.Looper.loop(Looper.java:123)
  E/WindowManager(  569):   at com.android.server.WindowManagerService$WMThread.run(WindowManagerService.java:440)
  I/WindowManager(  569): Out of memory for surface!  Looking for leaks...
  W/WindowManager(  569): No leaked surfaces; killing applicatons!
  W/ActivityManager(  569): Killing processes for memory at adjustment 0
  W/ActivityManager(  569): Killing for memory: ProcessRecord{436fec00 692:bitendian.bitmpc/10021} (adj 0)
  I/Process (  569): Sending signal. PID: 692 SIG: 9
  W/WindowManager(  569): Looks like we have reclaimed some memory, clearing surface for retry.
  W/SurfaceComposerClient(  569): Destroying surface while a transaction is open. Client 0x237d18: destroying surface 3, mTransactionOpen=1
  W/WindowManager(  569): Due to memory failure, waiting a bit for next layout
  I/ActivityManager(  569): Process bitendian.bitmpc (pid 692) has died.
  I/WindowManager(  569): WIN DEATH: Window{436bf740 bitendian.bitmpc/bitendian.bitmpc.activity.BitMPC paused=false}
  I/WindowManager(  569): WIN DEATH: Window{43745288 bitendian.bitmpc/bitendian.bitmpc.activity.BitMPC paused=false}
  I/WindowManager(  569): WIN DEATH: Window{436b2b30 bitendian.bitmpc/bitendian.bitmpc.activity.BitMPC paused=false}
  W/InputManagerService(  569): Got RemoteException sending setActive(false) notification to pid 692 uid 10021

**Comment by Jille** [comment]
Only seems to be a problem in my emulator. Ignoring.
